# Generated by Django 2.2.1 on 2019-05-15 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightlog',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lightlog',
            name='lights_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lightlog',
            name='lights_pulled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='light',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='light',
            name='on_order',
            field=models.IntegerField(default=0),
        ),
    ]
