# Generated by Django 2.2.1 on 2019-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0002_auto_20190515_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightlog',
            name='lights_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lightlog',
            name='lights_before',
            field=models.IntegerField(default=0),
        ),
    ]
